services:
  discovery-service:
    image: bbsebb/backend-discovery-service:latest
    container_name: discovery-service
    restart: unless-stopped
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: docker.gateway-service
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - "8761:8761"
    expose:
      - "8761"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 10s
      retries: 4
  config-service:
    image: bbsebb/backend-config-service:latest
    container_name: config-service
    restart: unless-stopped
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: docker.gateway-service
    ports:
      - "8888:8888"
    expose:
      - "8888"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DISCOVERY_SERVICE_URL=http://discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://config-service:8888
      - KEYSTORE_PASSWORD=${KEYSTORE_PASSWORD}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/actuator/health"]
      interval: 10s
      retries: 4
    depends_on:
      discovery-service:
        condition: service_healthy
  gateway-service:
    image: bbsebb/backend-gateway-service:latest
    container_name: gateway-service
    restart: unless-stopped
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: docker.gateway-service
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DISCOVERY_SERVICE_URL=http://discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://config-service:8888
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      retries: 4
    depends_on:
      config-service:
        condition: service_healthy
  contact-service:
    image: bbsebb/backend-contact-service:latest
    container_name: contact-service
    restart: unless-stopped
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: docker.contact-service
    ports:
      - "8082:8082"
    expose:
      - "8082"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DISCOVERY_SERVICE_URL=http://discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://config-service:8888
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/actuator/health"]
      interval: 10s
      retries: 4
    depends_on:
      gateway-service:
        condition: service_healthy
  instagram-service:
    image: bbsebb/backend-instagram-service:latest
    container_name: instagram-service
    restart: unless-stopped
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: docker.instagram-service
    ports:
      - "8083:8083"
    expose:
      - "8083"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DISCOVERY_SERVICE_URL=http://discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://config-service:8888
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8083/actuator/health" ]
      interval: 10s
      retries: 4
    depends_on:
      gateway-service:
        condition: service_healthy