services:
  postgres-dev:
    image: postgres:16.2
    container_name: postgres-dev-training
    environment:
      POSTGRES_DB: devdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_training_data:/var/lib/postgresql/data

volumes:
  postgres_dev_data:
