services:
  postgres-dev-instagram:
    image: postgres:16.2
    container_name: postgres-dev-instagram
    environment:
      POSTGRES_DB: devdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres_dev_instagram_data:/var/lib/postgresql/data

volumes:
  postgres_dev_instagram_data:
