apiVersion: apps/v1
kind: Deployment
metadata:
  name: instagram-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: instagram-service
  template:
    metadata:
      labels:
        app: instagram-service
    spec:
      containers:
      - name: instagram-service
        image: bbsebb/backend-instagram-service:v1
        ports:
        - containerPort: 8083
        env:
        - name: DISCOVERY_SERVICE_URL
          value: http://discovery-service:8761/eureka
        - name: CONFIG_SERVICE_URL
          value: http://config-service:8888
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8083
          initialDelaySeconds: 10
          periodSeconds: 10
          failureThreshold: 4
---
apiVersion: v1
kind: Service
metadata:
  name: instagram-service
spec:
  selector:
    app: instagram-service
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083