spring:
  application:
    name: training-service
  config:
    import: optional:configserver:${CONFIG_SERVICE_URL:http://localhost:8888}
server:
  port: 8084
springdoc:
  default-produces-media-type: application/prs.hal-forms+json
logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.http.converter.json: DEBUG
    com.fasterxml.jackson.databind: DEBUG