eureka:
  instance:
    prefer-ip-address: true  # Utilise l'adresse IP pour l'enregistrement au lieu du nom d'hôte
  client:
    enabled: true  # Active le client Eureka
    register-with-eureka: true
    fetchRegistry: true
    service-url:
      defaultZone: ${DISCOVERY_SERVICE_URL:http://localhost:8761/eureka}  # URL par défaut du service Eureka
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          clone-on-start: true
          uri: file://C:/Users/bbseb/Documents/programmation/ashs/backend/config-repository
server:
  port: ${PORT:8888}
encrypt:
  key-store:
    location: classpath:/keys/keystore.p12
    password: ${KEYSTORE_PASSWORD}
    alias: spring-config-encryption-key
    type: 'PKCS12'
